# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1474ce074be03dbf1dc91ec84f95b0398924dbbb56e3588b84769a2a888623ce8ab12552c60d70593dd580ce26e854890174dec1d293c889dc9be145fab8f29

test:
  secret_key_base: 49f8ba288a2c3f25f8817900cfc7c8561c6435fa83bca71f378c4509e009383721325e8994404f5399392efc57341e2c2eb02c2cffc3f91e076d38f7510ff404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
